<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-D1NECJQ" name="org.rerun.C" tests="8" failures="0" timestamp="20 Dec 2022 14:44:11 GMT" time="0.068" errors="1">
  <testcase name="testC1" time="0.007" classname="org.rerun.C">
    <skipped/>
  </testcase> <!-- testC1 -->
  <testcase name="testC1" time="0.027" classname="org.rerun.C">
    <skipped/>
  </testcase> <!-- testC1 -->
  <testcase name="testC3" time="0.002" classname="org.rerun.C"/>
  <testcase name="testC1" time="0.004" classname="org.rerun.C">
    <skipped/>
  </testcase> <!-- testC1 -->
  <testcase name="testC1" time="0.011" classname="org.rerun.C">
    <skipped/>
  </testcase> <!-- testC1 -->
  <testcase name="testC1" time="0.004" classname="org.rerun.C">
    <skipped/>
  </testcase> <!-- testC1 -->
  <testcase name="testC1" time="0.011" classname="org.rerun.C">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at org.rerun.C.testC1(C.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testC1 -->
  <testcase name="testC2" time="0.002" classname="org.rerun.C"/>
</testsuite> <!-- org.rerun.C -->
